{
    'name': 'Verts V16 imtac',
    'version': '16.0.1.0.0',
    'category': '',
    "sequence": 1,
    'complexity': "easy",
    'category': 'Generic Modules/OthersCreated',
    'license': "AGPL-3",
    'description': """ """,
    'author': 'Verts Services India Pvt. Ltd.',
    'website': 'www.verts.co.in',
    'depends': ['base', 'hr', 'project', 'services','budget'],
    'data': [
            'security/ir.model.access.csv',
            'security/security.xml',
            'views/pay_component_view.xml',
            'views/vacant_position_view.xml',
            # 'views/grade_budget_view.xml',
            'views/new_position_view.xml',
            'views/grade_view.xml',
            'views/hr_employee.xml',
            'views/employee_cont.xml',
            'views/grade_category.xml',
            'views/grade_budget_estimation.xml',
            'views/grade_job.xml',
            'views/grade_category_job_mapping.xml',
             'views/menu_item.xml',
             ],
    'test': [
    ],
    'qweb': [
    ],
    'installable': True,
    'auto_install': False,
}